apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cropdoctor

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- deployment.yaml
- service.yaml
- hpa.yaml
# - ingress.yaml  # Uncomment if using Ingress

commonLabels:
  app: cropdoctor
  version: v1
